* Use the same capitalization of the term "USBmount" consistently. * Mention that a 2.6 (or newer) kernel is required. * Explain that USBmount is not supposed to interact with a desktop   environment; refer to pmount and hal. * If configuration variables are not set by /etc/usbmount.conf,   /etc/dev.d/block/usbmount.dev no longer sets them to default values. * Create /var/run/usbmount when the package is installed, remove it when   the package is removed. * Include the string #DEBHELPER# in postinst and prerm. (Currently,   debhelper just replaces it with an empty line.)

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -2,13 +2,18 @@
 set -e
 
 # If the package is configured for the first time, try to create the
-# default mountpoints. Failure to do so is not considered fatal.
+# default mountpoints and /var/run/usbmount. Failure to do so is not
+# considered fatal.
 if test "$1" = configure && test "$2" = ""; then
     mkdir /media 2> /dev/null || :
     for i in 0 1 2 3 4 5 6 7; do
 	mkdir /media/usb$i 2> /dev/null || :
     done
     ln -s usb0 /media/usb 2> /dev/null || :
+
+    mkdir /var/run/usbmount 2> /dev/null || :
 fi
+
+#DEBHELPER#
 
 exit 0
diff --git a/debian/prerm b/debian/prerm
--- a/debian/prerm
+++ b/debian/prerm
@@ -1,13 +1,17 @@
 #!/bin/sh
 set -e
 
-# If the package is removed, try to remove the default mountpoints.
-# Failure to do so is not considered fatal.
+# If the package is removed, try to remove the default mountpoints and
+# /var/run/usbmount. Failure to do so is not considered fatal.
 if test "$1" = remove; then
     rm -f /media/usb 2> /dev/null || :
     for i in 0 1 2 3 4 5 6 7; do
 	rmdir /media/usb$i 2> /dev/null || :
     done
+
+    rm -fr /var/run/usbmount 2> /dev/null || :
 fi
+
+#DEBHELPER#
 
 exit 0
